# Generated by Django 5.1.4 on 2025-01-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reserved", models.DateField(verbose_name="Дата бронирования")),
                ("time_reserved", models.TimeField(verbose_name="Время бронирования")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Продолжительность бронирования"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Сообщение"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Бронирование активно"
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.CreateModel(
            name="BookingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reserved", models.DateField(verbose_name="Дата бронирования")),
                ("time_reserved", models.TimeField(verbose_name="Время бронирования")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Продолжительность бронирования"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Сообщение"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(verbose_name="Время отмены бронирования"),
                ),
            ],
            options={
                "verbose_name": "История бронирования",
                "verbose_name_plural": "История бронирований",
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(unique=True, verbose_name="Номер стола"),
                ),
                ("seats", models.IntegerField(verbose_name="Количество мест")),
                (
                    "is_booked",
                    models.BooleanField(default=False, verbose_name="Забронирован"),
                ),
            ],
            options={
                "verbose_name": "Стол",
                "verbose_name_plural": "Столы",
            },
        ),
    ]
